### ISSUE TITLE
サンプルが動作しない

### ISSUE THREAD

**Issue by HayatoMatsumuro** [HayatoMatsumuro/notopochi#5]
_現象_
　rails s を実行すると、以下のエラーが発生する。

_環境_
 Ruby : 2.0.0p647
 Rails 4.2.5

_動作の参考サイト_
　http://openbook4.me/projects/92/sections/488

```
=> Booting WEBrick
=> Rails 4.2.5 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
C:/Ruby200/lib/ruby/gems/2.0.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:182:i
n `rescue in create_default_data_source': No source of timezone data could be fo
und. (TZInfo::DataSourceNotFound)
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving th
is error.
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/tzinfo-1.2.2/lib/tzinfo/data_so
urce.rb:179:in `create_default_data_source'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/tzinfo-1.2.2/lib/tzinfo/data_so
urce.rb:40:in `block in get'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/tzinfo-1.2.2/lib/tzinfo/data_so
urce.rb:39:in `synchronize'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/tzinfo-1.2.2/lib/tzinfo/data_so
urce.rb:39:in `get'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/tzinfo-1.2.2/lib/tzinfo/timezon
e.rb:629:in `data_source'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/tzinfo-1.2.2/lib/tzinfo/timezon
e.rb:92:in `get'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/tzinfo-1.2.2/lib/tzinfo/timezon
e_proxy.rb:67:in `real_timezone'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/tzinfo-1.2.2/lib/tzinfo/timezon
e_proxy.rb:30:in `period_for_utc'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/tzinfo-1.2.2/lib/tzinfo/timezon
e.rb:549:in `current_period'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_
support/values/time_zone.rb:282:in `utc_offset'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_
support/values/time_zone.rb:243:in `block in []'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_
support/values/time_zone.rb:243:in `tap'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_
support/values/time_zone.rb:243:in `[]'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_
support/core_ext/time/zones.rb:61:in `find_zone!'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/activesupport-4.2.5/lib/active_
support/railtie.rb:20:in `block in <class:Railtie>'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/initia
lizable.rb:30:in `instance_exec'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/initia
lizable.rb:30:in `run'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/initia
lizable.rb:55:in `block in run_initializers'
        from C:/Ruby200/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
        from C:/Ruby200/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each
_strongly_connected_component'
        from C:/Ruby200/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_
component_from'
        from C:/Ruby200/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_c
onnected_component'
        from C:/Ruby200/lib/ruby/2.0.0/tsort.rb:180:in `each'
        from C:/Ruby200/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_
component'
        from C:/Ruby200/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/initia
lizable.rb:54:in `run_initializers'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/applic
ation.rb:352:in `initialize!'
        from c:/work/notopochi/config/environment.rb:5:in `<top (required)>'
        from c:/work/notopochi/config.ru:3:in `require'
        from c:/work/notopochi/config.ru:3:in `block in <main>'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:
55:in `instance_eval'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:
55:in `initialize'
        from c:/work/notopochi/config.ru:in `new'
        from c:/work/notopochi/config.ru:in `<main>'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:
49:in `eval'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:
49:in `new_from_string'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:
40:in `parse_file'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:2
99:in `build_app_and_options_from_config'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:2
08:in `app'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/comman
ds/server.rb:61:in `app'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:3
36:in `wrapped_app'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/comman
ds/server.rb:139:in `log_to_stdout'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/comman
ds/server.rb:78:in `start'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/comman
ds/commands_tasks.rb:80:in `block in server'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/comman
ds/commands_tasks.rb:75:in `tap'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/comman
ds/commands_tasks.rb:75:in `server'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/comman
ds/commands_tasks.rb:39:in `run_command!'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/railties-4.2.5/lib/rails/comman
ds.rb:17:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

**Comment by HayatoMatsumuro** [comment]
とりあえず、動作しました。
 tzinfo-data が問題っぽかった。

参考サイト
 https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors
1. gem 'tzinfo-data'　を実行
2. notopochi/Gemfile にgem 'tzinfo-data', platforms: [:mingw, :mswin] を記載( windows32bit の環境のため )

**Comment by HayatoMatsumuro** [comment]
windows 版だけなのか？Gemfileをコミットしてよいのか？？

**Comment by HayatoMatsumuro** [comment]
とりあえずコミットしない
